language: ruby
sudo: false
cache: bundler
bundler_args: --without development
rvm:
- jruby-1.7
env:
  - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug -J-Xms512m -J-Xmx512m"
script: bundle exec rspec
